version: "3"
services:
  django:
    build: .
    container_name: boho-back
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media
    restart: always
    command: sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/back-static
      - media_volume:/usr/src/app/back-media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  postgres_data:
